apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: postgres-honeypot
    type: postgres
    url: postgres:5432
    database: honeypot
    user: honeypot
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: false
